import { RoomStatus } from "@/enums/rooms.enum";
import { Rooms } from "@/interfaces/rooms.interface";

export const roomSeedData: Rooms[] = [
  {
    id: 1,
    name: "room 1",
    description: "This is room for 2 people.",
    type: "deluxe",
    top: "31.2%",
    left: "33%",
    status: RoomStatus.AVAILABLE,
    price: 5000,
    capacity: 2,
  },
  {
    id: 2,
    name: "room 2",
    description: "This is room for 2 people.",
    type: "deluxe",
    top: "31.9%",
    left: "41.3%",
    status: RoomStatus.AVAILABLE,
    price: 6000,
    capacity: 2,
  },
  {
    id: 3,
    name: "room 3",
    description: "This is room for 2 people.",
    type: "deluxe",
    top: "34.1%",
    left: "50.1%",
    status: RoomStatus.AVAILABLE,
    price: 7000,
    capacity: 2,
  },
  {
    id: 4,
    name: "room 4",
    description: "This is room for 5 people.",
    type: "family",
    top: "43.6%",
    left: "33.9%",
    status: RoomStatus.AVAILABLE,
    price: 8000,
    capacity: 5,
  },
  {
    id: 5,
    name: "room 5",
    description: "This is room for 5 people.",
    type: "family",
    top: "44.5%",
    left: "40.1%",
    status: RoomStatus.AVAILABLE,
    price: 9000,
    capacity: 5,
  },
  {
    id: 6,
    name: "room 6",
    description: "This is room for 5 people.",
    type: "family",
    top: "45%",
    left: "47.2%",
    status: RoomStatus.BOOKED,
    price: 10000,
    capacity: 5,
  },
  {
    id: 7,
    name: "room 7",
    description: "This is room for 5 people.",
    type: "family",
    top: "44.8%",
    left: "54.9%",
    status: RoomStatus.BOOKED,
    price: 11000,
    capacity: 5,
  },
  {
    id: 8,
    name: "room 8",
    description: "This is room for 5 people.",
    type: "family",
    top: "36.1%",
    left: "59.6%",
    status: RoomStatus.BOOKED,
    price: 12000,
    capacity: 5,
  },
  {
    id: 9,
    name: "room 9",
    description: "This is room for 5 people.",
    type: "family",
    top: "33.2%",
    left: "65.1%",
    status: RoomStatus.BOOKED,
    price: 13000,
    capacity: 5,
  },
  {
    id: 10,
    name: "room 10",
    description: "This is room for 5 people.",
    type: "family",
    top: "31.1%",
    left: "78.6%",
    status: RoomStatus.BOOKED,
    price: 14000,
    capacity: 5,
  },
  {
    id: 11,
    name: "room 11",
    description: "This is room for 5 people.",
    type: "family",
    top: "29.7%",
    left: "85.2%",
    status: RoomStatus.BOOKED,
    price: 15000,
    capacity: 5,
  },
  {
    id: 12,
    name: "room 12",
    description: "This is room for 5 people.",
    type: "family",
    top: "40.1%",
    left: "89.4%",
    status: RoomStatus.CLEANING,
    price: 16000,
    capacity: 5,
  },
  {
    id: 13,
    name: "room 13",
    description: "This is room for 5 people.",
    type: "family",
    top: "47.1%",
    left: "92.8%",
    status: RoomStatus.CLEANING,
    price: 17000,
    capacity: 5,
  },
  {
    id: 14,
    name: "room 14",
    description: "This is room for 3 people.",
    type: "standard",
    top: "60.4%",
    left: "47.8%",
    status: RoomStatus.CLEANING,
    price: 18000,
    capacity: 3,
  },
  {
    id: 15,
    name: "room 15",
    description: "This is room for 3 people.",
    type: "standard",
    top: "59.7%",
    left: "59.3%",
    status: RoomStatus.CLEANING,
    price: 19000,
    capacity: 3,
  },
  {
    id: 16,
    name: "room 16",
    description: "This is room for 3 people.",
    type: "standard",
    top: "55.9%",
    left: "66.7%",
    status: RoomStatus.CLEANING,
    price: 20000,
    capacity: 3,
  },
  {
    id: 17,
    name: "room 17",
    description: "This is room for 4 people.",
    type: "standard",
    top: "49.6%",
    left: "72.7%",
    status: RoomStatus.MAINTENANCE,
    price: 21000,
    capacity: 4,
  },
];
