import { RoomStatus } from "@/enums/rooms.enum";
import { Rooms } from "@/interfaces/rooms.interface";

export const roomSeedData: Rooms[] = [
  {
    id: 1,
    name: "Lakeside Retreat A",
    description:
      "Experience the epitome of comfort and luxury at our Deluxe Lakeside Retreats. Nestled amidst the tranquil beauty of the lake, these rooms offer breathtaking views and indulgent amenities. Each room is elegantly furnished with plush bedding, stylish décor, and modern conveniences to ensure a truly memorable stay. Whether you're seeking a romantic getaway or a peaceful retreat, our Deluxe Lakeside Retreats promise a haven of relaxation and rejuvenation.",
    type: "deluxe",
    top: "31.2%",
    left: "33%",
    status: RoomStatus.AVAILABLE,
    price: 5000,
    capacity: 2,
  },
  {
    id: 2,
    name: "Lakeside Retreat B",
    description:
      "Experience the epitome of comfort and luxury at our Deluxe Lakeside Retreats. Nestled amidst the tranquil beauty of the lake, these rooms offer breathtaking views and indulgent amenities. Each room is elegantly furnished with plush bedding, stylish décor, and modern conveniences to ensure a truly memorable stay. Whether you're seeking a romantic getaway or a peaceful retreat, our Deluxe Lakeside Retreats promise a haven of relaxation and rejuvenation.",
    type: "deluxe",
    top: "31.9%",
    left: "41.3%",
    status: RoomStatus.AVAILABLE,
    price: 6000,
    capacity: 2,
  },
  {
    id: 3,
    name: "Lakeside Retreat C",
    description:
      "Experience the epitome of comfort and luxury at our Deluxe Lakeside Retreats. Nestled amidst the tranquil beauty of the lake, these rooms offer breathtaking views and indulgent amenities. Each room is elegantly furnished with plush bedding, stylish décor, and modern conveniences to ensure a truly memorable stay. Whether you're seeking a romantic getaway or a peaceful retreat, our Deluxe Lakeside Retreats promise a haven of relaxation and rejuvenation.",
    type: "deluxe",
    top: "34.1%",
    left: "50.1%",
    status: RoomStatus.AVAILABLE,
    price: 7000,
    capacity: 2,
  },
  {
    id: 4,
    name: "Family Escape A",
    description:
      "Designed with families in mind, our Family Lakeside Havens provide the perfect blend of space, comfort, and convenience. These spacious rooms feature separate sleeping areas, ideal for accommodating families of all sizes. With thoughtful amenities and charming décor, our Family Lakeside Havens offer a welcoming retreat for bonding and creating lasting memories by the lake. Treat your loved ones to a delightful stay surrounded by nature's beauty.",
    type: "family",
    top: "43.6%",
    left: "33.9%",
    status: RoomStatus.AVAILABLE,
    price: 8000,
    capacity: 5,
  },
  {
    id: 5,
    name: "Family Escape B",
    description:
      "Designed with families in mind, our Family Lakeside Havens provide the perfect blend of space, comfort, and convenience. These spacious rooms feature separate sleeping areas, ideal for accommodating families of all sizes. With thoughtful amenities and charming décor, our Family Lakeside Havens offer a welcoming retreat for bonding and creating lasting memories by the lake. Treat your loved ones to a delightful stay surrounded by nature's beauty.",
    type: "family",
    top: "44.5%",
    left: "40.1%",
    status: RoomStatus.AVAILABLE,
    price: 9000,
    capacity: 5,
  },
  {
    id: 6,
    name: "Family Escape C",
    description:
      "Designed with families in mind, our Family Lakeside Havens provide the perfect blend of space, comfort, and convenience. These spacious rooms feature separate sleeping areas, ideal for accommodating families of all sizes. With thoughtful amenities and charming décor, our Family Lakeside Havens offer a welcoming retreat for bonding and creating lasting memories by the lake. Treat your loved ones to a delightful stay surrounded by nature's beauty.",
    type: "family",
    top: "45%",
    left: "47.2%",
    status: RoomStatus.BOOKED,
    price: 10000,
    capacity: 5,
  },
  {
    id: 7,
    name: "Family Escape D",
    description:
      "Designed with families in mind, our Family Lakeside Havens provide the perfect blend of space, comfort, and convenience. These spacious rooms feature separate sleeping areas, ideal for accommodating families of all sizes. With thoughtful amenities and charming décor, our Family Lakeside Havens offer a welcoming retreat for bonding and creating lasting memories by the lake. Treat your loved ones to a delightful stay surrounded by nature's beauty.",
    type: "family",
    top: "44.8%",
    left: "54.9%",
    status: RoomStatus.BOOKED,
    price: 11000,
    capacity: 5,
  },
  {
    id: 8,
    name: "Family Escape E",
    description:
      "Designed with families in mind, our Family Lakeside Havens provide the perfect blend of space, comfort, and convenience. These spacious rooms feature separate sleeping areas, ideal for accommodating families of all sizes. With thoughtful amenities and charming décor, our Family Lakeside Havens offer a welcoming retreat for bonding and creating lasting memories by the lake. Treat your loved ones to a delightful stay surrounded by nature's beauty.",
    type: "family",
    top: "36.1%",
    left: "59.6%",
    status: RoomStatus.BOOKED,
    price: 12000,
    capacity: 5,
  },
  {
    id: 9,
    name: "Family Escape F",
    description:
      "Designed with families in mind, our Family Lakeside Havens provide the perfect blend of space, comfort, and convenience. These spacious rooms feature separate sleeping areas, ideal for accommodating families of all sizes. With thoughtful amenities and charming décor, our Family Lakeside Havens offer a welcoming retreat for bonding and creating lasting memories by the lake. Treat your loved ones to a delightful stay surrounded by nature's beauty.",
    type: "family",
    top: "33.2%",
    left: "65.1%",
    status: RoomStatus.BOOKED,
    price: 13000,
    capacity: 5,
  },
  {
    id: 10,
    name: "Family Escape G",
    description:
      "Designed with families in mind, our Family Lakeside Havens provide the perfect blend of space, comfort, and convenience. These spacious rooms feature separate sleeping areas, ideal for accommodating families of all sizes. With thoughtful amenities and charming décor, our Family Lakeside Havens offer a welcoming retreat for bonding and creating lasting memories by the lake. Treat your loved ones to a delightful stay surrounded by nature's beauty.",
    type: "family",
    top: "31.1%",
    left: "78.6%",
    status: RoomStatus.BOOKED,
    price: 14000,
    capacity: 5,
  },
  {
    id: 11,
    name: "Family Escape H",
    description:
      "Designed with families in mind, our Family Lakeside Havens provide the perfect blend of space, comfort, and convenience. These spacious rooms feature separate sleeping areas, ideal for accommodating families of all sizes. With thoughtful amenities and charming décor, our Family Lakeside Havens offer a welcoming retreat for bonding and creating lasting memories by the lake. Treat your loved ones to a delightful stay surrounded by nature's beauty.",
    type: "family",
    top: "29.7%",
    left: "85.2%",
    status: RoomStatus.BOOKED,
    price: 15000,
    capacity: 5,
  },
  {
    id: 12,
    name: "Family Escape I",
    description:
      "Designed with families in mind, our Family Lakeside Havens provide the perfect blend of space, comfort, and convenience. These spacious rooms feature separate sleeping areas, ideal for accommodating families of all sizes. With thoughtful amenities and charming décor, our Family Lakeside Havens offer a welcoming retreat for bonding and creating lasting memories by the lake. Treat your loved ones to a delightful stay surrounded by nature's beauty.",
    type: "family",
    top: "40.1%",
    left: "89.4%",
    status: RoomStatus.CLEANING,
    price: 16000,
    capacity: 5,
  },
  {
    id: 13,
    name: "Family Escape J",
    description:
      "Designed with families in mind, our Family Lakeside Havens provide the perfect blend of space, comfort, and convenience. These spacious rooms feature separate sleeping areas, ideal for accommodating families of all sizes. With thoughtful amenities and charming décor, our Family Lakeside Havens offer a welcoming retreat for bonding and creating lasting memories by the lake. Treat your loved ones to a delightful stay surrounded by nature's beauty.",
    type: "family",
    top: "47.1%",
    left: "92.8%",
    status: RoomStatus.CLEANING,
    price: 17000,
    capacity: 5,
  },
  {
    id: 14,
    name: "Comfort Room A",
    description:
      "Embrace the essence of lakeside living in our Standard Lakeside Serenity rooms. Offering comfort and simplicity, these cozy accommodations are perfect for solo travelers or couples seeking a peaceful getaway. Admire stunning views of the lake from your private balcony or unwind in the comfort of your well-appointed room. With all the essentials for a relaxing stay, our Standard Lakeside Serenity rooms provide a tranquil escape amidst nature's beauty.",
    type: "standard",
    top: "60.4%",
    left: "47.8%",
    status: RoomStatus.CLEANING,
    price: 18000,
    capacity: 3,
  },
  {
    id: 15,
    name: "Comfort Room B",
    description:
      "Embrace the essence of lakeside living in our Standard Lakeside Serenity rooms. Offering comfort and simplicity, these cozy accommodations are perfect for solo travelers or couples seeking a peaceful getaway. Admire stunning views of the lake from your private balcony or unwind in the comfort of your well-appointed room. With all the essentials for a relaxing stay, our Standard Lakeside Serenity rooms provide a tranquil escape amidst nature's beauty.",
    type: "standard",
    top: "59.7%",
    left: "59.3%",
    status: RoomStatus.CLEANING,
    price: 19000,
    capacity: 3,
  },
  {
    id: 16,
    name: "Comfort Room C",
    description:
      "Embrace the essence of lakeside living in our Standard Lakeside Serenity rooms. Offering comfort and simplicity, these cozy accommodations are perfect for solo travelers or couples seeking a peaceful getaway. Admire stunning views of the lake from your private balcony or unwind in the comfort of your well-appointed room. With all the essentials for a relaxing stay, our Standard Lakeside Serenity rooms provide a tranquil escape amidst nature's beauty.",
    type: "standard",
    top: "55.9%",
    left: "66.7%",
    status: RoomStatus.CLEANING,
    price: 20000,
    capacity: 3,
  },
  {
    id: 17,
    name: "Comfort Room D",
    description: "This is room for 4 people.",
    type: "standard",
    top: "49.6%",
    left: "72.7%",
    status: RoomStatus.MAINTENANCE,
    price: 21000,
    capacity: 4,
  },
];
